<a href="https://colab.research.google.com/github/tracysmi/Pytorch-tutorial/blob/main/Pytorch_tutorial_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pytorch #2: Tensors

In [1]:
import torch
import numpy as np

# simple 2d Python List:
mylist = [[1,2,3,],[11,12,13]]

# numpy array:
np1 = np.random.rand(3,4)
np1.dtype   #dtype('float64')  default numpy float datatype

# Pytorch tensor
tensor_2d = torch.randn(3,4)
# tensor_2d.dtype   # torch.float32   default tensor float datatype
# tensor_2d

# create tensor from numpy array (keeps original numpy float datatype)
my_tensor = torch.tensor(np1)
my_tensor


tensor([[0.9340, 0.1222, 0.9041, 0.7472],
        [0.7958, 0.2710, 0.7106, 0.8045],
        [0.4458, 0.4690, 0.1587, 0.5434]], dtype=torch.float64)

Pytorch #3: Tensor operations

In [9]:
import torch
my_torch = torch.arange(10)
my_torch
# my_torch    # tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:

# Reshape and view; similar functions... and they update if underlying tensor is changed...
my_torch = my_torch.reshape(2,5)
my_torch
#tensor([[0, 1, 2, 3, 4],
#       [5, 6, 7, 8, 9]])


In [8]:

# Reshape when # of items not known:  -1
my_torch2 = torch.arange(15)
my_torch2 = my_torch2.reshape(3,-1)
my_torch2
# tensor([[ 0,  1,  2,  3,  4],
#        [ 5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14]])


tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])